const sounds={rain:{name:'雨落窗前',className:'rain',tone:.14},ocean:{name:'夜海潮汐',className:'ocean',tone:.08},brown:{name:'棕噪音',className:'brown',tone:.05},forest:{name:'林间微风',className:'forest',tone:.12}};
let ctx,gain,source,current='rain',playing=false,timerId,remaining=0,localTracks=[],activeLocal=null;
const $=s=>document.querySelector(s),playButton=$('#playButton'),trackName=$('#trackName'),miniArt=$('#miniArt'),volume=$('#volume'),volumeValue=$('#volumeValue'),timerMessage=$('#timerMessage'),audio=new Audio();
function makeNoise(){const b=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),d=b.getChannelData(0);let last=0;for(let i=0;i<d.length;i++){const w=Math.random()*2-1;if(current==='brown'){last=(last+.02*w)/1.02;d[i]=last*3.5}else if(current==='ocean')d[i]=w*.58+Math.sin(i/ctx.sampleRate*.18)*.22;else if(current==='forest')d[i]=w*.42+Math.sin(i/ctx.sampleRate*1.2)*.08;else d[i]=w}source=ctx.createBufferSource();source.buffer=b;source.loop=true;const f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=current==='rain'?2100:current==='forest'?1300:current==='ocean'?750:500;source.connect(f).connect(gain);source.start()}
function icon(on){playing=on;playButton.innerHTML=on?'<span>Ⅱ</span>':'<span>▶</span>';playButton.setAttribute('aria-label',on?'暂停':'播放')}
function start(){if(activeLocal!==null){audio.play();icon(true);return}if(!ctx){ctx=new AudioContext();gain=ctx.createGain();gain.connect(ctx.destination)}if(ctx.state==='suspended')ctx.resume();if(source)source.stop();makeNoise();updateVolume();icon(true)}function stop(){if(source){source.stop();source=null}audio.pause();icon(false)}
function updateVolume(){const v=+volume.value/100;if(gain)gain.gain.setTargetAtTime(v*sounds[current].tone,ctx.currentTime,.08);audio.volume=v;volumeValue.value=volume.value+'%';volumeValue.textContent=volume.value+'%'}
playButton.addEventListener('click',()=>playing?stop():start());volume.addEventListener('input',updateVolume);audio.addEventListener('ended',()=>icon(false));
document.querySelectorAll('.sound-card').forEach(c=>c.addEventListener('click',()=>{activeLocal=null;audio.pause();current=c.dataset.sound;document.querySelectorAll('.sound-card').forEach(x=>{x.classList.toggle('active',x===c);x.setAttribute('aria-pressed',x===c)});trackName.textContent=sounds[current].name;miniArt.className='mini-art '+sounds[current].className;miniArt.textContent=c.querySelector('.art').textContent;renderTracks();if(playing)start();updateVolume()}));
$('#timerActions').addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;document.querySelectorAll('#timerActions button').forEach(b=>b.classList.toggle('selected',b===e.target));clearInterval(timerId);remaining=+e.target.dataset.minutes*60;if(!remaining){timerMessage.textContent='未设置定时关闭';return}const render=()=>timerMessage.textContent=`将在约 ${Math.ceil(remaining/60)} 分钟后轻轻停止播放`;render();timerId=setInterval(()=>{if(--remaining<=0){clearInterval(timerId);stop();timerMessage.textContent='定时结束，晚安。'}else render()},1000)});
function renderTracks(){const list=$('#trackList');if(!localTracks.length){list.innerHTML='<p class="empty-state">还没有添加音乐。选择一首熟悉的旋律，留给今晚。</p>';return}list.innerHTML=localTracks.map((t,i)=>`<div class="music-track ${activeLocal===i?'active':''}" data-index="${i}"><span>♫</span><b>${t.name}</b><small>${t.size}</small><button class="remove" aria-label="移除 ${t.name}">×</button></div>`).join('')}
function playLocal(i){if(source){source.stop();source=null}activeLocal=i;const t=localTracks[i];audio.src=t.url;audio.play();trackName.textContent=t.name;miniArt.className='mini-art brown';miniArt.textContent='♫';document.querySelectorAll('.sound-card').forEach(c=>{c.classList.remove('active');c.setAttribute('aria-pressed','false')});renderTracks();icon(true);updateVolume()}
$('#musicInput').addEventListener('change',e=>{[...e.target.files].forEach(f=>localTracks.push({name:f.name.replace(/\.[^.]+$/,''),url:URL.createObjectURL(f),size:(f.size/1048576).toFixed(1)+' MB'}));e.target.value='';renderTracks()});
$('#trackList').addEventListener('click',e=>{const row=e.target.closest('.music-track');if(!row)return;const i=+row.dataset.index;if(e.target.closest('.remove')){if(activeLocal===i)stop();URL.revokeObjectURL(localTracks[i].url);localTracks.splice(i,1);activeLocal=null;renderTracks();return}playLocal(i)});
$('#backward').addEventListener('click',()=>activeLocal!==null?audio.currentTime=Math.max(0,audio.currentTime-10):!playing&&start());$('#forward').addEventListener('click',()=>activeLocal!==null?audio.currentTime+=10:!playing&&start());
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
